export const ADMIN_ROUTER = '/admin'
export const LOGIN_ROUTER = '/login'
export const REGISTRATION_ROUTER = '/registration'
export const MAIN_ROUTER = '/'
export const MUSIC_ROUTER = '/music'
export const ALL_MUSIC_ROUTER = '/allMusic'
export const ALL_MUSIC_ROUTER_GENRES = '/allMusic' + '/genre'
export const ALBUM_ROUTER = '/album'
export const GENRES_ROUTER = '/genres'
export const PROD_ROUTER = '/prod'
export const SERVICES_ROUTER = '/services'
export const ADD_BEATS = '/panel/addBeats'
export const ADD_ALBUM = '/panel/addAlbum'
export const ADD_SERVICE = '/panel/addService'
export const ERROR = '*'

export const REACT_APP_API_URL = 'http://45.147.176.80:8080/'